default_interval_secs = 5
default_timeout_millis = 500

[[hosts]]
id = "local"
address = "127.0.0.1"
interval_secs = 5

[[hosts.targets]]
id = "ssh"
port = 22
protocol = "tcp"
expected = "open"

[[hosts.targets]]
id = "bad-tcp"
port = 65000
protocol = "tcp"
expected = "closed"

[[hosts]]
id = "dns"
address = "8.8.8.8"

[[hosts.targets]]
id = "udp53"
port = 53
protocol = "udp"
expected = "open"
interval_secs = 10
